export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"

export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"

export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE"

export const POST_REQUEST = "POST_REQUEST"

export const POST_SUCCESS = "POST_SUCCESS"

export const POST_FAILURE = "POST_FAILURE"

export const GET_POST_REQUEST = "GET_POST_REQUEST"

export const GET_POST_SUCCESS = "GET_POST_SUCCESS"

export const GET_POST_FAILURE = "GET_POST_FAILURE"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"

export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE"

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST"

export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS"

export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE"

export const GET_SINGLE_POST_REQUEST = "GET_SINGLE_POST_REQUEST"

export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS"

export const GET_SINGLE_POST_FAILURE= "GET_SINGLE_POST_FAILURE"

